services:
  api:
    volumes:
      - ../:/app
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
    entrypoint: ["bash", "/app/docker/entrypoint.sh"]
    command: >
      uvicorn _api:app --host 0.0.0.0 --port 8000 --reload
      --reload-exclude outputs/**
      --reload-exclude outputs/**/*
      --reload-exclude data/**
      --reload-exclude data/**/*
      --reload-exclude model_ckpts/**
      --reload-exclude model_ckpts/**/*
      --reload-exclude wandb/**
      --reload-exclude wandb/**/*
